// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartphoneSecurityApplication.proto

package ds.adam.SmartphoneSecurityApplication;

public interface DoorLockOpenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartphoneSecurityApplication.DoorLockOpen)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SmartphoneSecurityApplication.DoorLockOpen.PassCode passCode = 1;</code>
   */
  int getPassCodeValue();
  /**
   * <code>.SmartphoneSecurityApplication.DoorLockOpen.PassCode passCode = 1;</code>
   */
  ds.adam.SmartphoneSecurityApplication.DoorLockOpen.PassCode getPassCode();

  /**
   * <code>int32 userAccept = 2;</code>
   */
  int getUserAccept();
}
