// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartphoneSecurityApplication.proto

package ds.adam.SmartphoneSecurityApplication;

/**
 * Protobuf type {@code SmartphoneSecurityApplication.DoorRequest}
 */
public  final class DoorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartphoneSecurityApplication.DoorRequest)
    DoorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoorRequest.newBuilder() to construct.
  private DoorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoorRequest() {
    visitorRequestCode1_ = 0;
    visitorRequestCode2_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DoorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            visitorRequestCode1_ = input.readInt32();
            break;
          }
          case 16: {

            visitorRequestCode2_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.adam.SmartphoneSecurityApplication.SmartphoneSecurityApplicationServiceImpl.internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.adam.SmartphoneSecurityApplication.SmartphoneSecurityApplicationServiceImpl.internal_static_SmartphoneSecurityApplication_DoorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.adam.SmartphoneSecurityApplication.DoorRequest.class, ds.adam.SmartphoneSecurityApplication.DoorRequest.Builder.class);
  }

  public static final int VISITORREQUESTCODE1_FIELD_NUMBER = 1;
  private int visitorRequestCode1_;
  /**
   * <code>int32 visitorRequestCode1 = 1;</code>
   */
  public int getVisitorRequestCode1() {
    return visitorRequestCode1_;
  }

  public static final int VISITORREQUESTCODE2_FIELD_NUMBER = 2;
  private int visitorRequestCode2_;
  /**
   * <code>int32 visitorRequestCode2 = 2;</code>
   */
  public int getVisitorRequestCode2() {
    return visitorRequestCode2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (visitorRequestCode1_ != 0) {
      output.writeInt32(1, visitorRequestCode1_);
    }
    if (visitorRequestCode2_ != 0) {
      output.writeInt32(2, visitorRequestCode2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (visitorRequestCode1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, visitorRequestCode1_);
    }
    if (visitorRequestCode2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, visitorRequestCode2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.adam.SmartphoneSecurityApplication.DoorRequest)) {
      return super.equals(obj);
    }
    ds.adam.SmartphoneSecurityApplication.DoorRequest other = (ds.adam.SmartphoneSecurityApplication.DoorRequest) obj;

    boolean result = true;
    result = result && (getVisitorRequestCode1()
        == other.getVisitorRequestCode1());
    result = result && (getVisitorRequestCode2()
        == other.getVisitorRequestCode2());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VISITORREQUESTCODE1_FIELD_NUMBER;
    hash = (53 * hash) + getVisitorRequestCode1();
    hash = (37 * hash) + VISITORREQUESTCODE2_FIELD_NUMBER;
    hash = (53 * hash) + getVisitorRequestCode2();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.SmartphoneSecurityApplication.DoorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.adam.SmartphoneSecurityApplication.DoorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SmartphoneSecurityApplication.DoorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartphoneSecurityApplication.DoorRequest)
      ds.adam.SmartphoneSecurityApplication.DoorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.adam.SmartphoneSecurityApplication.SmartphoneSecurityApplicationServiceImpl.internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.adam.SmartphoneSecurityApplication.SmartphoneSecurityApplicationServiceImpl.internal_static_SmartphoneSecurityApplication_DoorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.adam.SmartphoneSecurityApplication.DoorRequest.class, ds.adam.SmartphoneSecurityApplication.DoorRequest.Builder.class);
    }

    // Construct using ds.adam.SmartphoneSecurityApplication.DoorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      visitorRequestCode1_ = 0;

      visitorRequestCode2_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.adam.SmartphoneSecurityApplication.SmartphoneSecurityApplicationServiceImpl.internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor;
    }

    @java.lang.Override
    public ds.adam.SmartphoneSecurityApplication.DoorRequest getDefaultInstanceForType() {
      return ds.adam.SmartphoneSecurityApplication.DoorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.adam.SmartphoneSecurityApplication.DoorRequest build() {
      ds.adam.SmartphoneSecurityApplication.DoorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.adam.SmartphoneSecurityApplication.DoorRequest buildPartial() {
      ds.adam.SmartphoneSecurityApplication.DoorRequest result = new ds.adam.SmartphoneSecurityApplication.DoorRequest(this);
      result.visitorRequestCode1_ = visitorRequestCode1_;
      result.visitorRequestCode2_ = visitorRequestCode2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.adam.SmartphoneSecurityApplication.DoorRequest) {
        return mergeFrom((ds.adam.SmartphoneSecurityApplication.DoorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.adam.SmartphoneSecurityApplication.DoorRequest other) {
      if (other == ds.adam.SmartphoneSecurityApplication.DoorRequest.getDefaultInstance()) return this;
      if (other.getVisitorRequestCode1() != 0) {
        setVisitorRequestCode1(other.getVisitorRequestCode1());
      }
      if (other.getVisitorRequestCode2() != 0) {
        setVisitorRequestCode2(other.getVisitorRequestCode2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.adam.SmartphoneSecurityApplication.DoorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.adam.SmartphoneSecurityApplication.DoorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int visitorRequestCode1_ ;
    /**
     * <code>int32 visitorRequestCode1 = 1;</code>
     */
    public int getVisitorRequestCode1() {
      return visitorRequestCode1_;
    }
    /**
     * <code>int32 visitorRequestCode1 = 1;</code>
     */
    public Builder setVisitorRequestCode1(int value) {
      
      visitorRequestCode1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 visitorRequestCode1 = 1;</code>
     */
    public Builder clearVisitorRequestCode1() {
      
      visitorRequestCode1_ = 0;
      onChanged();
      return this;
    }

    private int visitorRequestCode2_ ;
    /**
     * <code>int32 visitorRequestCode2 = 2;</code>
     */
    public int getVisitorRequestCode2() {
      return visitorRequestCode2_;
    }
    /**
     * <code>int32 visitorRequestCode2 = 2;</code>
     */
    public Builder setVisitorRequestCode2(int value) {
      
      visitorRequestCode2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 visitorRequestCode2 = 2;</code>
     */
    public Builder clearVisitorRequestCode2() {
      
      visitorRequestCode2_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartphoneSecurityApplication.DoorRequest)
  }

  // @@protoc_insertion_point(class_scope:SmartphoneSecurityApplication.DoorRequest)
  private static final ds.adam.SmartphoneSecurityApplication.DoorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.adam.SmartphoneSecurityApplication.DoorRequest();
  }

  public static ds.adam.SmartphoneSecurityApplication.DoorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoorRequest>
      PARSER = new com.google.protobuf.AbstractParser<DoorRequest>() {
    @java.lang.Override
    public DoorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DoorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DoorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.adam.SmartphoneSecurityApplication.DoorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

