// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartphoneSecurityApplication.proto

package ds.adam.SmartphoneSecurityApplication;

public interface DoorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartphoneSecurityApplication.DoorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 visitorRequestCode1 = 1;</code>
   */
  int getVisitorRequestCode1();

  /**
   * <code>int32 visitorRequestCode2 = 2;</code>
   */
  int getVisitorRequestCode2();
}
