// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartphoneSecurityApplication.proto

package ds.adam.SmartphoneSecurityApplication;

public final class SmartphoneSecurityApplicationServiceImpl {
  private SmartphoneSecurityApplicationServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartphoneSecurityApplication_DoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartphoneSecurityApplication_DoorLockOpen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartphoneSecurityApplication_DoorLockOpen_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#SmartphoneSecurityApplication.proto\022\035S" +
      "martphoneSecurityApplication\"G\n\013DoorRequ" +
      "est\022\033\n\023visitorRequestCode1\030\001 \001(\005\022\033\n\023visi" +
      "torRequestCode2\030\002 \001(\005\"\233\001\n\014DoorLockOpen\022F" +
      "\n\010passCode\030\001 \001(\01624.SmartphoneSecurityApp" +
      "lication.DoorLockOpen.PassCode\022\022\n\nuserAc" +
      "cept\030\002 \001(\005\"/\n\010PassCode\022\t\n\005error\020\000\022\013\n\007fai" +
      "lure\020\001\022\013\n\007success\020\0022\224\001\n$SmartphoneSecuri" +
      "tyApplicationService\022l\n\rvisitorUnlock\022*." +
      "SmartphoneSecurityApplication.DoorReques" +
      "t\032+.SmartphoneSecurityApplication.DoorLo" +
      "ckOpen\"\0000\001BS\n%ds.adam.SmartphoneSecurity" +
      "ApplicationB(SmartphoneSecurityApplicati" +
      "onServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartphoneSecurityApplication_DoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartphoneSecurityApplication_DoorRequest_descriptor,
        new java.lang.String[] { "VisitorRequestCode1", "VisitorRequestCode2", });
    internal_static_SmartphoneSecurityApplication_DoorLockOpen_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartphoneSecurityApplication_DoorLockOpen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartphoneSecurityApplication_DoorLockOpen_descriptor,
        new java.lang.String[] { "PassCode", "UserAccept", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
