// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

/**
 * Protobuf type {@code VideoDoorbell.BellRequest}
 */
public  final class BellRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VideoDoorbell.BellRequest)
    BellRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BellRequest.newBuilder() to construct.
  private BellRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BellRequest() {
    connectionIntervals_ = 0;
    visual_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BellRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            connectionIntervals_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            visual_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_BellRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_BellRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.adam.VideoDoorbell.BellRequest.class, ds.adam.VideoDoorbell.BellRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code VideoDoorbell.BellRequest.Visual}
   */
  public enum Visual
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DISCONNECTED = 0;</code>
     */
    DISCONNECTED(0),
    /**
     * <code>CONNECTED = 1;</code>
     */
    CONNECTED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DISCONNECTED = 0;</code>
     */
    public static final int DISCONNECTED_VALUE = 0;
    /**
     * <code>CONNECTED = 1;</code>
     */
    public static final int CONNECTED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Visual valueOf(int value) {
      return forNumber(value);
    }

    public static Visual forNumber(int value) {
      switch (value) {
        case 0: return DISCONNECTED;
        case 1: return CONNECTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Visual>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Visual> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Visual>() {
            public Visual findValueByNumber(int number) {
              return Visual.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ds.adam.VideoDoorbell.BellRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Visual[] VALUES = values();

    public static Visual valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Visual(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:VideoDoorbell.BellRequest.Visual)
  }

  public static final int CONNECTIONINTERVALS_FIELD_NUMBER = 1;
  private int connectionIntervals_;
  /**
   * <code>int32 connectionIntervals = 1;</code>
   */
  public int getConnectionIntervals() {
    return connectionIntervals_;
  }

  public static final int VISUAL_FIELD_NUMBER = 2;
  private int visual_;
  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
   */
  public int getVisualValue() {
    return visual_;
  }
  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
   */
  public ds.adam.VideoDoorbell.BellRequest.Visual getVisual() {
    @SuppressWarnings("deprecation")
    ds.adam.VideoDoorbell.BellRequest.Visual result = ds.adam.VideoDoorbell.BellRequest.Visual.valueOf(visual_);
    return result == null ? ds.adam.VideoDoorbell.BellRequest.Visual.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (connectionIntervals_ != 0) {
      output.writeInt32(1, connectionIntervals_);
    }
    if (visual_ != ds.adam.VideoDoorbell.BellRequest.Visual.DISCONNECTED.getNumber()) {
      output.writeEnum(2, visual_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (connectionIntervals_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, connectionIntervals_);
    }
    if (visual_ != ds.adam.VideoDoorbell.BellRequest.Visual.DISCONNECTED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, visual_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.adam.VideoDoorbell.BellRequest)) {
      return super.equals(obj);
    }
    ds.adam.VideoDoorbell.BellRequest other = (ds.adam.VideoDoorbell.BellRequest) obj;

    boolean result = true;
    result = result && (getConnectionIntervals()
        == other.getConnectionIntervals());
    result = result && visual_ == other.visual_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNECTIONINTERVALS_FIELD_NUMBER;
    hash = (53 * hash) + getConnectionIntervals();
    hash = (37 * hash) + VISUAL_FIELD_NUMBER;
    hash = (53 * hash) + visual_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.BellRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.adam.VideoDoorbell.BellRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VideoDoorbell.BellRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoDoorbell.BellRequest)
      ds.adam.VideoDoorbell.BellRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_BellRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_BellRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.adam.VideoDoorbell.BellRequest.class, ds.adam.VideoDoorbell.BellRequest.Builder.class);
    }

    // Construct using ds.adam.VideoDoorbell.BellRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      connectionIntervals_ = 0;

      visual_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_BellRequest_descriptor;
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.BellRequest getDefaultInstanceForType() {
      return ds.adam.VideoDoorbell.BellRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.BellRequest build() {
      ds.adam.VideoDoorbell.BellRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.BellRequest buildPartial() {
      ds.adam.VideoDoorbell.BellRequest result = new ds.adam.VideoDoorbell.BellRequest(this);
      result.connectionIntervals_ = connectionIntervals_;
      result.visual_ = visual_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.adam.VideoDoorbell.BellRequest) {
        return mergeFrom((ds.adam.VideoDoorbell.BellRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.adam.VideoDoorbell.BellRequest other) {
      if (other == ds.adam.VideoDoorbell.BellRequest.getDefaultInstance()) return this;
      if (other.getConnectionIntervals() != 0) {
        setConnectionIntervals(other.getConnectionIntervals());
      }
      if (other.visual_ != 0) {
        setVisualValue(other.getVisualValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.adam.VideoDoorbell.BellRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.adam.VideoDoorbell.BellRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int connectionIntervals_ ;
    /**
     * <code>int32 connectionIntervals = 1;</code>
     */
    public int getConnectionIntervals() {
      return connectionIntervals_;
    }
    /**
     * <code>int32 connectionIntervals = 1;</code>
     */
    public Builder setConnectionIntervals(int value) {
      
      connectionIntervals_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 connectionIntervals = 1;</code>
     */
    public Builder clearConnectionIntervals() {
      
      connectionIntervals_ = 0;
      onChanged();
      return this;
    }

    private int visual_ = 0;
    /**
     * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
     */
    public int getVisualValue() {
      return visual_;
    }
    /**
     * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
     */
    public Builder setVisualValue(int value) {
      visual_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
     */
    public ds.adam.VideoDoorbell.BellRequest.Visual getVisual() {
      @SuppressWarnings("deprecation")
      ds.adam.VideoDoorbell.BellRequest.Visual result = ds.adam.VideoDoorbell.BellRequest.Visual.valueOf(visual_);
      return result == null ? ds.adam.VideoDoorbell.BellRequest.Visual.UNRECOGNIZED : result;
    }
    /**
     * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
     */
    public Builder setVisual(ds.adam.VideoDoorbell.BellRequest.Visual value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      visual_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
     */
    public Builder clearVisual() {
      
      visual_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VideoDoorbell.BellRequest)
  }

  // @@protoc_insertion_point(class_scope:VideoDoorbell.BellRequest)
  private static final ds.adam.VideoDoorbell.BellRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.adam.VideoDoorbell.BellRequest();
  }

  public static ds.adam.VideoDoorbell.BellRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BellRequest>
      PARSER = new com.google.protobuf.AbstractParser<BellRequest>() {
    @java.lang.Override
    public BellRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BellRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BellRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BellRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.adam.VideoDoorbell.BellRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

