// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

public interface BellRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.BellRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 connectionIntervals = 1;</code>
   */
  int getConnectionIntervals();

  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
   */
  int getVisualValue();
  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 2;</code>
   */
  ds.adam.VideoDoorbell.BellRequest.Visual getVisual();
}
