// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

public interface DoorLockStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.DoorLockStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string check = 1;</code>
   */
  java.lang.String getCheck();
  /**
   * <code>string check = 1;</code>
   */
  com.google.protobuf.ByteString
      getCheckBytes();

  /**
   * <code>float result = 2;</code>
   */
  float getResult();
}
