// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

public interface DoorLockTamperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.DoorLockTamper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intruder = 1;</code>
   */
  int getIntruder();
}
