// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

/**
 * Protobuf type {@code VideoDoorbell.DoorLockStatus}
 */
public  final class DoorLockStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VideoDoorbell.DoorLockStatus)
    DoorLockStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoorLockStatus.newBuilder() to construct.
  private DoorLockStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoorLockStatus() {
    check_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DoorLockStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            check_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_DoorLockStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_DoorLockStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.adam.VideoDoorbell.DoorLockStatus.class, ds.adam.VideoDoorbell.DoorLockStatus.Builder.class);
  }

  public static final int CHECK_FIELD_NUMBER = 1;
  private boolean check_;
  /**
   * <code>bool check = 1;</code>
   */
  public boolean getCheck() {
    return check_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (check_ != false) {
      output.writeBool(1, check_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (check_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, check_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.adam.VideoDoorbell.DoorLockStatus)) {
      return super.equals(obj);
    }
    ds.adam.VideoDoorbell.DoorLockStatus other = (ds.adam.VideoDoorbell.DoorLockStatus) obj;

    boolean result = true;
    result = result && (getCheck()
        == other.getCheck());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHECK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCheck());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.adam.VideoDoorbell.DoorLockStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.adam.VideoDoorbell.DoorLockStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code VideoDoorbell.DoorLockStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoDoorbell.DoorLockStatus)
      ds.adam.VideoDoorbell.DoorLockStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_DoorLockStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_DoorLockStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.adam.VideoDoorbell.DoorLockStatus.class, ds.adam.VideoDoorbell.DoorLockStatus.Builder.class);
    }

    // Construct using ds.adam.VideoDoorbell.DoorLockStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      check_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.adam.VideoDoorbell.VideoDoorbellServiceImpl.internal_static_VideoDoorbell_DoorLockStatus_descriptor;
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.DoorLockStatus getDefaultInstanceForType() {
      return ds.adam.VideoDoorbell.DoorLockStatus.getDefaultInstance();
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.DoorLockStatus build() {
      ds.adam.VideoDoorbell.DoorLockStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.adam.VideoDoorbell.DoorLockStatus buildPartial() {
      ds.adam.VideoDoorbell.DoorLockStatus result = new ds.adam.VideoDoorbell.DoorLockStatus(this);
      result.check_ = check_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.adam.VideoDoorbell.DoorLockStatus) {
        return mergeFrom((ds.adam.VideoDoorbell.DoorLockStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.adam.VideoDoorbell.DoorLockStatus other) {
      if (other == ds.adam.VideoDoorbell.DoorLockStatus.getDefaultInstance()) return this;
      if (other.getCheck() != false) {
        setCheck(other.getCheck());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.adam.VideoDoorbell.DoorLockStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.adam.VideoDoorbell.DoorLockStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean check_ ;
    /**
     * <code>bool check = 1;</code>
     */
    public boolean getCheck() {
      return check_;
    }
    /**
     * <code>bool check = 1;</code>
     */
    public Builder setCheck(boolean value) {
      
      check_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool check = 1;</code>
     */
    public Builder clearCheck() {
      
      check_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VideoDoorbell.DoorLockStatus)
  }

  // @@protoc_insertion_point(class_scope:VideoDoorbell.DoorLockStatus)
  private static final ds.adam.VideoDoorbell.DoorLockStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.adam.VideoDoorbell.DoorLockStatus();
  }

  public static ds.adam.VideoDoorbell.DoorLockStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoorLockStatus>
      PARSER = new com.google.protobuf.AbstractParser<DoorLockStatus>() {
    @java.lang.Override
    public DoorLockStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DoorLockStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DoorLockStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoorLockStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.adam.VideoDoorbell.DoorLockStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

