// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool videoConfimrationFromBell = 2;</code>
   */
  boolean getVideoConfimrationFromBell();
}
