# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Alarm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41larm.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0fUnwantedVisitor\x12\x10\n\x08isLocked\x18\x01 \x01(\x08\"M\n\x07Speaker\x12\x13\n\x0bsoundSystem\x18\x01 \x01(\x05\x12-\n\tsirenTime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp28\n\x0c\x41larmService\x12(\n\x08\x64oorLock\x12\x10.UnwantedVisitor\x1a\x08.Speaker\"\x00\x62\x06proto3')



_UNWANTEDVISITOR = DESCRIPTOR.message_types_by_name['UnwantedVisitor']
_SPEAKER = DESCRIPTOR.message_types_by_name['Speaker']
UnwantedVisitor = _reflection.GeneratedProtocolMessageType('UnwantedVisitor', (_message.Message,), {
  'DESCRIPTOR' : _UNWANTEDVISITOR,
  '__module__' : 'Alarm_pb2'
  # @@protoc_insertion_point(class_scope:UnwantedVisitor)
  })
_sym_db.RegisterMessage(UnwantedVisitor)

Speaker = _reflection.GeneratedProtocolMessageType('Speaker', (_message.Message,), {
  'DESCRIPTOR' : _SPEAKER,
  '__module__' : 'Alarm_pb2'
  # @@protoc_insertion_point(class_scope:Speaker)
  })
_sym_db.RegisterMessage(Speaker)

_ALARMSERVICE = DESCRIPTOR.services_by_name['AlarmService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNWANTEDVISITOR._serialized_start=48
  _UNWANTEDVISITOR._serialized_end=83
  _SPEAKER._serialized_start=85
  _SPEAKER._serialized_end=162
  _ALARMSERVICE._serialized_start=164
  _ALARMSERVICE._serialized_end=220
# @@protoc_insertion_point(module_scope)
