# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmartphoneSecurityApplication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#SmartphoneSecurityApplication.proto\x12\x1dSmartphoneSecurityApplication\"G\n\x0b\x44oorRequest\x12\x1b\n\x13visitorRequestCode1\x18\x01 \x01(\x05\x12\x1b\n\x13visitorRequestCode2\x18\x02 \x01(\x05\"\x9b\x01\n\x0c\x44oorLockOpen\x12\x46\n\x08passCode\x18\x01 \x01(\x0e\x32\x34.SmartphoneSecurityApplication.DoorLockOpen.PassCode\x12\x12\n\nuserAccept\x18\x02 \x01(\x05\"/\n\x08PassCode\x12\t\n\x05\x65rror\x10\x00\x12\x0b\n\x07\x66\x61ilure\x10\x01\x12\x0b\n\x07success\x10\x02\x32\x94\x01\n$SmartphoneSecurityApplicationService\x12l\n\rvisitorUnlock\x12*.SmartphoneSecurityApplication.DoorRequest\x1a+.SmartphoneSecurityApplication.DoorLockOpen\"\x00\x30\x01\x42S\n%ds.adam.SmartphoneSecurityApplicationB(SmartphoneSecurityApplicationServiceImplP\x01\x62\x06proto3')



_DOORREQUEST = DESCRIPTOR.message_types_by_name['DoorRequest']
_DOORLOCKOPEN = DESCRIPTOR.message_types_by_name['DoorLockOpen']
_DOORLOCKOPEN_PASSCODE = _DOORLOCKOPEN.enum_types_by_name['PassCode']
DoorRequest = _reflection.GeneratedProtocolMessageType('DoorRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOORREQUEST,
  '__module__' : 'SmartphoneSecurityApplication_pb2'
  # @@protoc_insertion_point(class_scope:SmartphoneSecurityApplication.DoorRequest)
  })
_sym_db.RegisterMessage(DoorRequest)

DoorLockOpen = _reflection.GeneratedProtocolMessageType('DoorLockOpen', (_message.Message,), {
  'DESCRIPTOR' : _DOORLOCKOPEN,
  '__module__' : 'SmartphoneSecurityApplication_pb2'
  # @@protoc_insertion_point(class_scope:SmartphoneSecurityApplication.DoorLockOpen)
  })
_sym_db.RegisterMessage(DoorLockOpen)

_SMARTPHONESECURITYAPPLICATIONSERVICE = DESCRIPTOR.services_by_name['SmartphoneSecurityApplicationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%ds.adam.SmartphoneSecurityApplicationB(SmartphoneSecurityApplicationServiceImplP\001'
  _DOORREQUEST._serialized_start=70
  _DOORREQUEST._serialized_end=141
  _DOORLOCKOPEN._serialized_start=144
  _DOORLOCKOPEN._serialized_end=299
  _DOORLOCKOPEN_PASSCODE._serialized_start=252
  _DOORLOCKOPEN_PASSCODE._serialized_end=299
  _SMARTPHONESECURITYAPPLICATIONSERVICE._serialized_start=302
  _SMARTPHONESECURITYAPPLICATIONSERVICE._serialized_end=450
# @@protoc_insertion_point(module_scope)
