# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SmartphoneSecurityApplication_pb2 as SmartphoneSecurityApplication__pb2


class SmartphoneSecurityApplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.visitorUnlock = channel.unary_stream(
                '/SmartphoneSecurityApplication.SmartphoneSecurityApplicationService/visitorUnlock',
                request_serializer=SmartphoneSecurityApplication__pb2.DoorRequest.SerializeToString,
                response_deserializer=SmartphoneSecurityApplication__pb2.DoorLockOpen.FromString,
                )


class SmartphoneSecurityApplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def visitorUnlock(self, request, context):
        """Server-Side Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartphoneSecurityApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'visitorUnlock': grpc.unary_stream_rpc_method_handler(
                    servicer.visitorUnlock,
                    request_deserializer=SmartphoneSecurityApplication__pb2.DoorRequest.FromString,
                    response_serializer=SmartphoneSecurityApplication__pb2.DoorLockOpen.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartphoneSecurityApplication.SmartphoneSecurityApplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartphoneSecurityApplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def visitorUnlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SmartphoneSecurityApplication.SmartphoneSecurityApplicationService/visitorUnlock',
            SmartphoneSecurityApplication__pb2.DoorRequest.SerializeToString,
            SmartphoneSecurityApplication__pb2.DoorLockOpen.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
