# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoDoorbell.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13VideoDoorbell.proto\x12\rVideoDoorbell\"*\n\x05Video\x12!\n\x19videoConfimrationFromBell\x18\x02 \x01(\x08\"\x88\x01\n\x0b\x42\x65llRequest\x12\x1b\n\x13\x63onnectionIntervals\x18\x01 \x01(\x05\x12\x31\n\x06visual\x18\x02 \x01(\x0e\x32!.VideoDoorbell.BellRequest.Visual\")\n\x06Visual\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01\"\x1f\n\x0e\x44oorLockStatus\x12\r\n\x05\x63heck\x18\x01 \x01(\x08\"\"\n\x0e\x44oorLockTamper\x12\x10\n\x08intruder\x18\x01 \x01(\x08\x32\xab\x01\n\x14VideoDoorbellService\x12\x43\n\thomeVideo\x12\x14.VideoDoorbell.Video\x1a\x1a.VideoDoorbell.BellRequest\"\x00(\x01\x30\x01\x12N\n\ndoorStatus\x12\x1d.VideoDoorbell.DoorLockStatus\x1a\x1d.VideoDoorbell.DoorLockTamper\"\x00(\x01\x42\x33\n\x15\x64s.adam.VideoDoorbellB\x18VideoDoorbellServiceImplP\x01\x62\x06proto3')



_VIDEO = DESCRIPTOR.message_types_by_name['Video']
_BELLREQUEST = DESCRIPTOR.message_types_by_name['BellRequest']
_DOORLOCKSTATUS = DESCRIPTOR.message_types_by_name['DoorLockStatus']
_DOORLOCKTAMPER = DESCRIPTOR.message_types_by_name['DoorLockTamper']
_BELLREQUEST_VISUAL = _BELLREQUEST.enum_types_by_name['Visual']
Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'VideoDoorbell_pb2'
  # @@protoc_insertion_point(class_scope:VideoDoorbell.Video)
  })
_sym_db.RegisterMessage(Video)

BellRequest = _reflection.GeneratedProtocolMessageType('BellRequest', (_message.Message,), {
  'DESCRIPTOR' : _BELLREQUEST,
  '__module__' : 'VideoDoorbell_pb2'
  # @@protoc_insertion_point(class_scope:VideoDoorbell.BellRequest)
  })
_sym_db.RegisterMessage(BellRequest)

DoorLockStatus = _reflection.GeneratedProtocolMessageType('DoorLockStatus', (_message.Message,), {
  'DESCRIPTOR' : _DOORLOCKSTATUS,
  '__module__' : 'VideoDoorbell_pb2'
  # @@protoc_insertion_point(class_scope:VideoDoorbell.DoorLockStatus)
  })
_sym_db.RegisterMessage(DoorLockStatus)

DoorLockTamper = _reflection.GeneratedProtocolMessageType('DoorLockTamper', (_message.Message,), {
  'DESCRIPTOR' : _DOORLOCKTAMPER,
  '__module__' : 'VideoDoorbell_pb2'
  # @@protoc_insertion_point(class_scope:VideoDoorbell.DoorLockTamper)
  })
_sym_db.RegisterMessage(DoorLockTamper)

_VIDEODOORBELLSERVICE = DESCRIPTOR.services_by_name['VideoDoorbellService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025ds.adam.VideoDoorbellB\030VideoDoorbellServiceImplP\001'
  _VIDEO._serialized_start=38
  _VIDEO._serialized_end=80
  _BELLREQUEST._serialized_start=83
  _BELLREQUEST._serialized_end=219
  _BELLREQUEST_VISUAL._serialized_start=178
  _BELLREQUEST_VISUAL._serialized_end=219
  _DOORLOCKSTATUS._serialized_start=221
  _DOORLOCKSTATUS._serialized_end=252
  _DOORLOCKTAMPER._serialized_start=254
  _DOORLOCKTAMPER._serialized_end=288
  _VIDEODOORBELLSERVICE._serialized_start=291
  _VIDEODOORBELLSERVICE._serialized_end=462
# @@protoc_insertion_point(module_scope)
