// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.DublinSuburb22;

public interface BellRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.BellRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 exampleNumber2 = 2;</code>
   */
  int getExampleNumber2();

  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 3;</code>
   */
  int getVisualValue();
  /**
   * <code>.VideoDoorbell.BellRequest.Visual visual = 3;</code>
   */
  ds.adam.DublinSuburb22.BellRequest.Visual getVisual();
}
