// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.DublinSuburb22;

public final class VideoDoorbellServiceImpl {
  private VideoDoorbellServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoDoorbell_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoDoorbell_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoDoorbell_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoDoorbell_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoDoorbell_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoDoorbell_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VideoDoorbell_BellRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VideoDoorbell_BellRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023VideoDoorbell.proto\022\rVideoDoorbell\"\300\001\n" +
      "\020CalculateRequest\022\017\n\007number1\030\001 \001(\002\022\017\n\007nu" +
      "mber2\030\002 \001(\002\022<\n\toperation\030\003 \001(\0162).VideoDo" +
      "orbell.CalculateRequest.Operation\"L\n\tOpe" +
      "ration\022\014\n\010ADDITION\020\000\022\017\n\013SUBTRACTION\020\001\022\022\n" +
      "\016MULTIPLICATION\020\002\022\014\n\010DIVISION\020\003\"4\n\021Calcu" +
      "lateResponse\022\016\n\006result\030\001 \001(\002\022\017\n\007message\030" +
      "\002 \001(\t\"\037\n\005Video\022\026\n\016exampleNumber1\030\001 \001(\005\"\201" +
      "\001\n\013BellRequest\022\026\n\016exampleNumber2\030\002 \001(\005\0221" +
      "\n\006visual\030\003 \001(\0162!.VideoDoorbell.BellReque" +
      "st.Visual\"\'\n\006Visual\022\t\n\005GREEN\020\000\022\007\n\003RED\020\002\022" +
      "\t\n\005ERROR\020\0032\255\001\n\024VideoDoorbellService\022P\n\tc" +
      "alculate\022\037.VideoDoorbell.CalculateReques" +
      "t\032 .VideoDoorbell.CalculateResponse\"\000\022C\n" +
      "\thomeVideo\022\024.VideoDoorbell.Video\032\032.Video" +
      "Doorbell.BellRequest\"\000(\0010\001B3\n\025ds.adam.Vi" +
      "deoDoorbellB\030VideoDoorbellServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VideoDoorbell_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VideoDoorbell_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoDoorbell_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_VideoDoorbell_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VideoDoorbell_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoDoorbell_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_VideoDoorbell_Video_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VideoDoorbell_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoDoorbell_Video_descriptor,
        new java.lang.String[] { "ExampleNumber1", });
    internal_static_VideoDoorbell_BellRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_VideoDoorbell_BellRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VideoDoorbell_BellRequest_descriptor,
        new java.lang.String[] { "ExampleNumber2", "Visual", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
