// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.DublinSuburb22;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 exampleNumber1 = 1;</code>
   */
  int getExampleNumber1();
}
