// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoDoorbell.proto

package ds.adam.VideoDoorbell;

public interface CalculateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDoorbell.CalculateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float result = 1;</code>
   */
  float getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
